"""initial quiz schema"""
from alembic import op
import sqlalchemy as sa
revision = '3d8f1afb02f2'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_owner'), ['owner'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('a', sa.Text(), nullable=False),
    sa.Column('b', sa.Text(), nullable=False),
    sa.Column('c', sa.Text(), nullable=False),
    sa.Column('d', sa.Text(), nullable=False),
    sa.Column('correct', sa.String(length=1), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint("correct IN ('A','B','C','D')"),
    sa.CheckConstraint("level IN ('Básico','Intermediário','Avançado')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('attempt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=1), nullable=True),
    sa.CheckConstraint("answer IS NULL OR answer IN ('A','B','C','D')"),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'position'),
    sa.UniqueConstraint('attempt_id', 'question_id')
    )
    with op.batch_alter_table('attempt_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_items_attempt_id'), ['attempt_id'], unique=False)

    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_items_attempt_id'))

    op.drop_table('attempt_items')
    op.drop_table('questions')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_owner'))

    op.drop_table('attempts')
    # ### end Alembic commands ###
