name: Orkflow Scheduller

on:
  schedule:
    - cron: '0 15 * * *'

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Schedule step
        run: |
          echo "Workflow executado via scheduller! Data e hora atual: $(date)"